### PR TITLE
Refactored plugin

### PR DESCRIPTION
**Pull request by stellarhoof**
Hey there @enomsg. I was using your plugin but noticed some bugs and decided to refactor it. In part to learn how conceal works :). The user now can specify their own conceals. Isn't that cool? Hope it proves useful!

### CODE REVIEW

**Comment by enomsg** [comment]
Hi! Looking at the code, this is really cool rework, thanks a lot! However, I've tried to test it quickly and nothing is concealed (I did add the snippet from readme to my .vimrc). I bet this is something on my side and I'll try to figure out what is happening later, but if you have any idea (maybe something else I should add?), please let me know. :)

**Comment by azure-satellite** [comment]
Yeah. Sorry. I forgot that I left the decision of highlighting and setting `conceallevel` to the user. Just add this after loading the syntax file:

```
	hi link concealedOperator Operator
	hi! link Conceal Operator
	setlocal conceallevel=2
```
The highlighting definitions we could include in the syntax file, but I think `conceallevel` should be left to the user. Any thoughts?

**Comment by enomsg** [comment]
Yay, it seem to work! Thanks!

As for enabling things by default... Personally I like the initial setup to be as simple as possible (prefereably one git clone command into ~/.vim, as it is currently in the master branch). It makes things up and running quickly. (Plus, if somebody would not want the concealing, she would probably not have the plugin installed in the first place.. so enabling it by default seems like a good idea to me.)

It is definitely burdensome to require to cut-n-paste the concealing rules from the README to .vimrc... So, how about moving the definitions from README.md to something like, contrib/default.vim, and including it by default on startup? Changable via say haskell_conceal_scheme. E.g. haskell_conceal_scheme="someuserscheme" in .vimrc would change the scheme from contrib/default.vim to contrib/someuserscheme.vim. Contrib directory would be really nice as we can customize things independently and/or share concealing/notation ideas, instead of keeping them in our privite .vimrc's (e.g. I quite liked the idea of prepending F/A/M to lifts).

**Comment by azure-satellite** [comment]
Yeah I really like that. I think its a great idea! Kind of like snippets that users can share. If it's good it will get incorporated into this repo. Too bad this is not Ultisnips or Neosnippets :(. Then it could be really fun. 
I saw that you had a link to https://www.fpcomplete.com/school/to-infinity-and-beyond/pick-of-the-week/guide-to-ghc-extensions/basic-syntax-extensions#unicodesyntax in your comments and checked out. I love the idea of having Unicode operators in Haskell's source for my personal projects. The problem is that typing `C-V u[unicode code]` is kind of tedious. As it is copying and pasting Unicode characters. Then I thought it would be great to have some function parse the Pragma at the top and if `{-# LANGUAGE UnicodeSyntax #-}` is present, define a bunch of Vim's abbreviations so that when you type, the code gets substituted by the actual characters.

**Comment by enomsg** [comment]
Sorry for the delay, I've got really swamped by other projects. I surely like all of your ideas. It is just it takes time to implement them. I cannot merge the code right now as the rework is not a drop-in replacement for the current concealing schemes. I'll try to move current concealing rules to use your code, but feel free to beat me to it. :)

**Comment by victoredwardocallaghan** [comment]
I'm looking forward to this merge, just saying :)

**Comment by enomsg** [comment]
Me too. :) I really like it.

But again, it has to provide easy means to use it. Right now if I'd merge it, the installation would be quite difficult. Plus, it does not support all of the current schemes of concealing. I kinda feel lazy to do "fix" these nitpicks myself considering that the current code just works. :)

**Comment by voidzero** [comment]
@azure-satellite Wonder if you plan on continuing to develop this?

**Comment by azure-satellite** [comment]
Yeah. About two weeks from now I have some free time I will use to close this for good!

**Pull request closed without merging**
