### PR TITLE
Add concealment for mappend (without backticks)

### PR DESCRIPTION
**Pull request by centromere**

### CODE REVIEW

**Comment by centromere** [comment]
Any chance this may be merged in?

**Comment by enomsg** [comment]
@centromere , thanks for the contribution and sorry for the delay.

I'm a bit concerned that the following two cases will end up being same visually, but produce two different results. E.g.

```map (mappend "a") ["b"]``` -> `map (⊕ "a") ["b"]` -> `["ab"]`
```map (`mappend` "a") ["b"] ```-> `map (⊕ "a") ["b"]` -> `["ba"]`

Note that we "solved" this problem for `lift`-like functions by concealing spaces, e.g.

`fmap a b` -> `↥a b`

Since there is no space, in Haskell we can think of `↥f` as "lifted f", just another function name.

And this one has spaces:

```a `fmap` b``` -> `a ↥ b`

So it is clear that there's an infix lift-like operation in between, there is no ambiguity (unless someone types ``` `fmap`b ```, but this can be fixed, I guess.)

Not sure how to solve it for `mappend`. I would probably advice to always use backticks as it's clear whether it's `a +` or `+ a`.

If we still want to have non-backticked mappend concealment, I think it will need to have an option for enable/disable.

**Comment by enomsg** [comment]
I think I will merge this PR as-is, but it'd be nice to make it a configurable option. Feel free to submit another PR if you want to do it, or I can do it in coming days... :)

**Comment by centromere** [comment]
Thank you!

**Pull request merged**
